// AUTO GENERATED by svelte-reflector. DO NOT EDIT.
import api from "$lib/api";
import { PUBLIC_ENVIRONMENT } from "$env/static/public";
import {
  Behavior,
  isFormValid,
  type ApiErrorResponse,
} from "$reflector/reflector.svelte";

import { UserDto, type UserResInterface, UserRes } from "./user.schema.svelte";

export abstract class UserModule {
  loading = $state<boolean>(false);
  forms = $state({
    create: new UserDto(),
  });

  constructor(params?: { empty: boolean }) {
    const isEmpty = params?.empty ?? PUBLIC_ENVIRONMENT !== "DEV";
    this.forms = this.buildForms(isEmpty);
  }

  private buildForms(isEmpty: boolean) {
    if (!isEmpty) return this.forms;

    return { create: new UserDto({ empty: true }) };
  }

  /**  */
  protected async _createRun(params?: {
    behavior?: Behavior<UserResInterface, ApiErrorResponse>;
  }) {
    const behavior = params?.behavior ?? new Behavior();
    const { onError, onSuccess } = behavior;

    this.loading = true;

    const endpoint = `users`;

    const data = this.forms.create.bundle();

    try {
      const response = await api.post<UserResInterface>({
        endpoint,
        data,
      });

      await onSuccess?.(response);

      return { ok: true, data: new UserRes({ data: response }) };
    } catch (e) {
      let parsedError: ApiErrorResponse;
      try {
        parsedError = JSON.parse((e as Error).message) as ApiErrorResponse;
      } catch {
        parsedError = {
          error: "unknown",
          message: (e as Error).message ?? String(e),
        };
      }
      await onError?.(parsedError);
      return { ok: false, error: parsedError };
    } finally {
      this.loading = false;
    }
  }

  /** @deprecated use `_createRun()` — returns a discriminated ApiResult */
  protected async _create(params?: {
    behavior?: Behavior<UserResInterface, ApiErrorResponse>;
  }) {
    const res = await this._createRun(params);
    return res.ok ? res.data : undefined;
  }

  protected clearForms() {
    this.forms.create.reset();
  }

  protected reset() {
    this.clearForms();
  }
}
