// AUTO GENERATED by svelte-reflector. DO NOT EDIT.
import api from "$lib/api";
import { PUBLIC_ENVIRONMENT } from "$env/static/public";
import { page } from "$app/state";
import {
  Behavior,
  genericArrayBundler,
  isFormValid,
  QueryBuilder,
  type ApiErrorResponse,
  setQueryGroup,
} from "$reflector/reflector.svelte";
import mockedParams from "$reflector/mocked-params.svelte";

import {
  type PackageTenantController_listResponseInterface,
  PackageTenantController_listResponse,
  type PackageInterface,
  Package,
  type PackageTenantController_listResponse2Interface,
  PackageTenantController_listResponse2,
  type ControllerItemInterface,
  ControllerItem,
  PackageTenantController_updateBody,
} from "./package-tenant.schema.svelte";

class Querys {
  readonly page = $derived(new QueryBuilder({ key: "page" }));
  readonly limit = $derived(new QueryBuilder({ key: "limit" }));

  constructor() {
    setQueryGroup([
      { key: "page", value: 1 },
      { key: "limit", value: 10 },
    ]);
  }

  bundle() {
    return {
      page: this.page?.value,
      limit: this.limit?.value,
    };
  }
}
class Paths {
  readonly packageId = $derived.by(() =>
    "packageId" in page.params ? page.params.packageId : mockedParams.packageId,
  ) as string | null;
  readonly controllerId = $derived.by(() =>
    "controllerId" in page.params
      ? page.params.controllerId
      : mockedParams.controllerId,
  ) as string | null;
}

export abstract class PackageTenantModule {
  loading = $state<boolean>(false);
  totalPages = $state<number>(1);
  listPackages = $state<PackageTenantController_listResponse["data"]>([]);
  bundledListPackages = $derived(genericArrayBundler(this.listPackages));
  packageEntity = $state<Package | undefined>();
  listControllers = $state<PackageTenantController_listResponse2["data"]>([]);
  bundledListControllers = $derived(genericArrayBundler(this.listControllers));
  controllerItem = $state<ControllerItem | undefined>();
  querys = new Querys();
  paths = new Paths();
  forms = $state({
    update: new PackageTenantController_updateBody(),
  });

  constructor(params?: { empty: boolean }) {
    const isEmpty = params?.empty ?? PUBLIC_ENVIRONMENT !== "DEV";
    this.forms = this.buildForms(isEmpty);
  }

  private buildForms(isEmpty: boolean) {
    if (!isEmpty) return this.forms;

    return { update: new PackageTenantController_updateBody({ empty: true }) };
  }

  /**  */
  protected async _listAllPackages(params?: {
    behavior?: Behavior<
      PackageTenantController_listResponseInterface,
      ApiErrorResponse
    >;
  }) {
    const behavior = params?.behavior ?? new Behavior();
    const { onError, onSuccess } = behavior;

    this.loading = true;
    const { page, limit } = this.querys.bundle();
    const endpoint = `tenant/package`;

    try {
      const response = await api.get<
        PackageTenantController_listResponseInterface,
        unknown
      >({
        endpoint,
        queryData: { page, limit },
      });
      this.listPackages = PackageTenantController_listResponse.from(
        response.data,
      );
      this.totalPages = response.totalPages;

      await onSuccess?.(response);

      return this.listPackages;
    } catch (e) {
      let parsedError: ApiErrorResponse;
      try {
        parsedError = JSON.parse((e as Error).message) as ApiErrorResponse;
      } catch {
        parsedError = {
          error: "unknown",
          message: (e as Error).message ?? String(e),
        };
      }
      return await onError?.(parsedError);
    } finally {
      this.loading = false;
    }
  }

  /**  */
  protected async _findOnePackage(params?: {
    behavior?: Behavior<PackageInterface, ApiErrorResponse>;
    paths?: {
      packageId: string;
    };
  }) {
    const behavior = params?.behavior ?? new Behavior();
    const { onError, onSuccess } = behavior;

    this.loading = true;
    const { packageId } = params?.paths ?? this.paths;
    const endpoint = `tenant/package/${packageId}`;

    try {
      const response = await api.get<PackageInterface, unknown>({
        endpoint,
      });

      this.packageEntity = new Package({ data: response });

      await onSuccess?.(response);

      return new Package({ data: response });
    } catch (e) {
      let parsedError: ApiErrorResponse;
      try {
        parsedError = JSON.parse((e as Error).message) as ApiErrorResponse;
      } catch {
        parsedError = {
          error: "unknown",
          message: (e as Error).message ?? String(e),
        };
      }
      return await onError?.(parsedError);
    } finally {
      this.loading = false;
    }
  }

  /**  */
  protected async _listAllControllers(params?: {
    behavior?: Behavior<
      PackageTenantController_listResponse2Interface,
      ApiErrorResponse
    >;
    paths?: {
      packageId: string;
    };
  }) {
    const behavior = params?.behavior ?? new Behavior();
    const { onError, onSuccess } = behavior;

    this.loading = true;
    const { page } = this.querys.bundle();
    const { packageId } = params?.paths ?? this.paths;
    const endpoint = `tenant/package/${packageId}/controller`;

    try {
      const response = await api.get<
        PackageTenantController_listResponse2Interface,
        unknown
      >({
        endpoint,
        queryData: { page },
      });
      this.listControllers = PackageTenantController_listResponse2.from(
        response.data,
      );
      this.totalPages = response.totalPages;

      await onSuccess?.(response);

      return this.listControllers;
    } catch (e) {
      let parsedError: ApiErrorResponse;
      try {
        parsedError = JSON.parse((e as Error).message) as ApiErrorResponse;
      } catch {
        parsedError = {
          error: "unknown",
          message: (e as Error).message ?? String(e),
        };
      }
      return await onError?.(parsedError);
    } finally {
      this.loading = false;
    }
  }

  /**  */
  protected async _findOneController(params?: {
    behavior?: Behavior<ControllerItemInterface, ApiErrorResponse>;
    paths?: {
      packageId: string;
      controllerId: string;
    };
  }) {
    const behavior = params?.behavior ?? new Behavior();
    const { onError, onSuccess } = behavior;

    this.loading = true;
    const { packageId, controllerId } = params?.paths ?? this.paths;
    const endpoint = `tenant/package/${packageId}/controller/${controllerId}`;

    try {
      const response = await api.get<ControllerItemInterface, unknown>({
        endpoint,
      });

      this.controllerItem = new ControllerItem({ data: response });

      await onSuccess?.(response);

      return new ControllerItem({ data: response });
    } catch (e) {
      let parsedError: ApiErrorResponse;
      try {
        parsedError = JSON.parse((e as Error).message) as ApiErrorResponse;
      } catch {
        parsedError = {
          error: "unknown",
          message: (e as Error).message ?? String(e),
        };
      }
      return await onError?.(parsedError);
    } finally {
      this.loading = false;
    }
  }

  /**  */
  protected async _update(params?: {
    behavior?: Behavior<ControllerItemInterface, ApiErrorResponse>;
    paths?: {
      packageId: string;
      controllerId: string;
    };
  }) {
    const behavior = params?.behavior ?? new Behavior();
    const { onError, onSuccess } = behavior;

    this.loading = true;
    const { packageId, controllerId } = params?.paths ?? this.paths;
    const endpoint = `tenant/package/${packageId}/controller/${controllerId}`;

    const data = this.forms.update.bundle();

    try {
      const response = await api.patch<ControllerItemInterface>({
        endpoint,
        data,
      });

      await onSuccess?.(response);

      return new ControllerItem({ data: response });
    } catch (e) {
      let parsedError: ApiErrorResponse;
      try {
        parsedError = JSON.parse((e as Error).message) as ApiErrorResponse;
      } catch {
        parsedError = {
          error: "unknown",
          message: (e as Error).message ?? String(e),
        };
      }
      return await onError?.(parsedError);
    } finally {
      this.loading = false;
    }
  }

  protected clearListPackages() {
    this.listPackages = [];
  }

  protected clearPackageEntity() {
    this.packageEntity = undefined;
  }

  protected clearListControllers() {
    this.listControllers = [];
  }

  protected clearControllerItem() {
    this.controllerItem = undefined;
  }

  protected clearQuerys() {
    this.querys = new Querys();
  }

  protected clearPaths() {
    this.paths = new Paths();
  }

  protected clearForms() {
    this.forms = this.buildForms(true);
  }

  protected reset() {
    this.clearListPackages();
    this.clearPackageEntity();
    this.clearListControllers();
    this.clearControllerItem();
    this.clearQuerys();
    this.clearPaths();
    this.clearForms();
  }
}
