// AUTO GENERATED by svelte-reflector. DO NOT EDIT.
import api from "$lib/api";
import { PUBLIC_ENVIRONMENT } from "$env/static/public";
import {
  Behavior,
  isFormValid,
  QueryBuilder,
  bundleStrict,
  type ApiErrorResponse,
} from "$reflector/reflector.svelte";

import { ENUM_TENANT_ENTITY_STATE } from "$reflector/enums";
import {
  type TenantAddressInterface,
  TenantAddress,
  MunicipalityBackOffice,
  type UserResInterface,
  UserRes,
} from "./tenant.schema.svelte";

class Querys {
  readonly state = new QueryBuilder({ key: "state" });

  bundle() {
    return bundleStrict({
      state: this.state?.value,
    });
  }
}

export abstract class TenantModule {
  loading = $state<boolean>(false);
  tenantAddress = $state<TenantAddress | undefined>();
  querys = new Querys();
  forms = $state({
    create: new MunicipalityBackOffice(),
  });

  constructor(params?: { empty: boolean }) {
    const isEmpty = params?.empty ?? PUBLIC_ENVIRONMENT !== "DEV";
    this.forms = this.buildForms(isEmpty);
  }

  private buildForms(isEmpty: boolean) {
    if (!isEmpty) return this.forms;

    return { create: new MunicipalityBackOffice({ empty: true }) };
  }

  /**  */
  protected async _listAllRun(params?: {
    behavior?: Behavior<TenantAddressInterface, ApiErrorResponse>;
    queryOverride?: {
      state?: string | null;
    };
  }) {
    const behavior = params?.behavior ?? new Behavior();
    const { onError, onSuccess } = behavior;

    this.loading = true;
    const { state } = params?.queryOverride ?? this.querys.bundle();
    const endpoint = `tenants`;

    try {
      const response = await api.get<TenantAddressInterface, unknown>({
        endpoint,
        queryData: { state },
      });

      this.tenantAddress = new TenantAddress({ data: response });

      await onSuccess?.(response);

      return { ok: true, data: new TenantAddress({ data: response }) };
    } catch (e) {
      let parsedError: ApiErrorResponse;
      try {
        parsedError = JSON.parse((e as Error).message) as ApiErrorResponse;
      } catch {
        parsedError = {
          error: "unknown",
          message: (e as Error).message ?? String(e),
        };
      }
      await onError?.(parsedError);
      return { ok: false, error: parsedError };
    } finally {
      this.loading = false;
    }
  }

  /** @deprecated use `_listAllRun()` — returns a discriminated ApiResult */
  protected async _listAll(params?: {
    behavior?: Behavior<TenantAddressInterface, ApiErrorResponse>;
    queryOverride?: {
      state?: string | null;
    };
  }) {
    const res = await this._listAllRun(params);
    return res.ok ? res.data : undefined;
  }

  /**  */
  protected async _createRun(params?: {
    behavior?: Behavior<UserResInterface, ApiErrorResponse>;
  }) {
    const behavior = params?.behavior ?? new Behavior();
    const { onError, onSuccess } = behavior;

    this.loading = true;

    const endpoint = `tenants`;

    const data = this.forms.create.bundle();

    try {
      const response = await api.post<UserResInterface>({
        endpoint,
        data,
      });

      await onSuccess?.(response);

      return { ok: true, data: new UserRes({ data: response }) };
    } catch (e) {
      let parsedError: ApiErrorResponse;
      try {
        parsedError = JSON.parse((e as Error).message) as ApiErrorResponse;
      } catch {
        parsedError = {
          error: "unknown",
          message: (e as Error).message ?? String(e),
        };
      }
      await onError?.(parsedError);
      return { ok: false, error: parsedError };
    } finally {
      this.loading = false;
    }
  }

  /** @deprecated use `_createRun()` — returns a discriminated ApiResult */
  protected async _create(params?: {
    behavior?: Behavior<UserResInterface, ApiErrorResponse>;
  }) {
    const res = await this._createRun(params);
    return res.ok ? res.data : undefined;
  }

  protected clearTenantAddress() {
    this.tenantAddress = undefined;
  }

  protected clearQuerys() {
    this.querys = new Querys();
  }

  protected clearForms() {
    this.forms.create.reset();
  }

  protected reset() {
    this.clearTenantAddress();
    this.clearQuerys();
    this.clearForms();
  }
}
