// AUTO GENERATED by svelte-reflector. DO NOT EDIT.
import api from "$lib/api";
import { PUBLIC_ENVIRONMENT } from "$env/static/public";
import { page } from "$app/state";
import {
  Behavior,
  isFormValid,
  QueryBuilder,
  bundleStrict,
  type ApiErrorResponse,
} from "$reflector/reflector.svelte";
import mockedParams from "$reflector/mocked-params.svelte";

import {
  type UserController_listResponseInterface,
  UserController_listResponse,
  UserController_createBody,
  type UserInterface,
  User,
} from "./user.schema.svelte";

class Querys {
  readonly limit = new QueryBuilder({ key: "limit", defaultValue: 10 });

  bundle() {
    return bundleStrict({
      limit: this.limit?.value,
    });
  }
}
class Paths {
  readonly id = $derived.by(() =>
    "id" in page.params ? page.params.id : mockedParams.id,
  ) as string | null;
}

export abstract class UserModule {
  loading = $state<boolean>(false);
  userController_list = $state<UserController_listResponse | undefined>();
  userEntity = $state<User | undefined>();
  querys = new Querys();
  paths = new Paths();
  forms = $state({
    create: new UserController_createBody(),
  });

  constructor(params?: { empty: boolean }) {
    const isEmpty = params?.empty ?? PUBLIC_ENVIRONMENT !== "DEV";
    this.forms = this.buildForms(isEmpty);
  }

  private buildForms(isEmpty: boolean) {
    if (!isEmpty) return this.forms;

    return { create: new UserController_createBody({ empty: true }) };
  }

  /**  */
  protected async _listAllRun(params?: {
    behavior?: Behavior<UserController_listResponseInterface, ApiErrorResponse>;
    queryOverride?: {
      limit?: string | null;
    };
  }) {
    const behavior = params?.behavior ?? new Behavior();
    const { onError, onSuccess } = behavior;

    this.loading = true;
    const { limit } = params?.queryOverride ?? this.querys.bundle();
    const endpoint = `users`;

    try {
      const response = await api.get<
        UserController_listResponseInterface,
        unknown
      >({
        endpoint,
        queryData: { limit },
      });

      this.userController_list = new UserController_listResponse({
        data: response,
      });

      await onSuccess?.(response);

      return {
        ok: true,
        data: new UserController_listResponse({ data: response }),
      };
    } catch (e) {
      let parsedError: ApiErrorResponse;
      try {
        parsedError = JSON.parse((e as Error).message) as ApiErrorResponse;
      } catch {
        parsedError = {
          error: "unknown",
          message: (e as Error).message ?? String(e),
        };
      }
      await onError?.(parsedError);
      return { ok: false, error: parsedError };
    } finally {
      this.loading = false;
    }
  }

  /** @deprecated use `_listAllRun()` — returns a discriminated ApiResult */
  protected async _listAll(params?: {
    behavior?: Behavior<UserController_listResponseInterface, ApiErrorResponse>;
    queryOverride?: {
      limit?: string | null;
    };
  }) {
    const res = await this._listAllRun(params);
    return res.ok ? res.data : undefined;
  }

  /**  */
  protected async _createRun(params?: {
    behavior?: Behavior<UserInterface, ApiErrorResponse>;
  }) {
    const behavior = params?.behavior ?? new Behavior();
    const { onError, onSuccess } = behavior;

    this.loading = true;

    const endpoint = `users`;

    const data = this.forms.create.bundle();

    try {
      const response = await api.post<UserInterface>({
        endpoint,
        data,
      });

      await onSuccess?.(response);

      return { ok: true, data: new User({ data: response }) };
    } catch (e) {
      let parsedError: ApiErrorResponse;
      try {
        parsedError = JSON.parse((e as Error).message) as ApiErrorResponse;
      } catch {
        parsedError = {
          error: "unknown",
          message: (e as Error).message ?? String(e),
        };
      }
      await onError?.(parsedError);
      return { ok: false, error: parsedError };
    } finally {
      this.loading = false;
    }
  }

  /** @deprecated use `_createRun()` — returns a discriminated ApiResult */
  protected async _create(params?: {
    behavior?: Behavior<UserInterface, ApiErrorResponse>;
  }) {
    const res = await this._createRun(params);
    return res.ok ? res.data : undefined;
  }

  /**  */
  protected async _entityRun(params?: {
    behavior?: Behavior<UserInterface, ApiErrorResponse>;
    paths?: {
      id: string;
    };
  }) {
    const behavior = params?.behavior ?? new Behavior();
    const { onError, onSuccess } = behavior;

    this.loading = true;
    const { id } = params?.paths ?? this.paths;
    const endpoint = `users/${id}`;

    try {
      const response = await api.get<UserInterface, unknown>({
        endpoint,
      });

      this.userEntity = new User({ data: response });

      await onSuccess?.(response);

      return { ok: true, data: new User({ data: response }) };
    } catch (e) {
      let parsedError: ApiErrorResponse;
      try {
        parsedError = JSON.parse((e as Error).message) as ApiErrorResponse;
      } catch {
        parsedError = {
          error: "unknown",
          message: (e as Error).message ?? String(e),
        };
      }
      await onError?.(parsedError);
      return { ok: false, error: parsedError };
    } finally {
      this.loading = false;
    }
  }

  /** @deprecated use `_entityRun()` — returns a discriminated ApiResult */
  protected async _entity(params?: {
    behavior?: Behavior<UserInterface, ApiErrorResponse>;
    paths?: {
      id: string;
    };
  }) {
    const res = await this._entityRun(params);
    return res.ok ? res.data : undefined;
  }

  /**  */
  protected async _removeRun(params?: {
    behavior?: Behavior<null, ApiErrorResponse>;
    paths?: {
      id: string;
    };
  }) {
    const behavior = params?.behavior ?? new Behavior();
    const { onError, onSuccess } = behavior;

    this.loading = true;
    const { id } = params?.paths ?? this.paths;
    const endpoint = `users/${id}`;

    try {
      const response = await api.delete<null, unknown>({
        endpoint,
      });

      await onSuccess?.(response);

      return { ok: true, data: null };
    } catch (e) {
      let parsedError: ApiErrorResponse;
      try {
        parsedError = JSON.parse((e as Error).message) as ApiErrorResponse;
      } catch {
        parsedError = {
          error: "unknown",
          message: (e as Error).message ?? String(e),
        };
      }
      await onError?.(parsedError);
      return { ok: false, error: parsedError };
    } finally {
      this.loading = false;
    }
  }

  /** @deprecated use `_removeRun()` — returns a discriminated ApiResult */
  protected async _remove(params?: {
    behavior?: Behavior<null, ApiErrorResponse>;
    paths?: {
      id: string;
    };
  }) {
    const res = await this._removeRun(params);
    return res.ok ? res.data : undefined;
  }

  protected clearUserController_list() {
    this.userController_list = undefined;
  }

  protected clearUserEntity() {
    this.userEntity = undefined;
  }

  protected clearQuerys() {
    this.querys = new Querys();
  }

  protected clearPaths() {
    this.paths = new Paths();
  }

  protected clearForms() {
    this.forms.create.reset();
  }

  protected reset() {
    this.clearUserController_list();
    this.clearUserEntity();
    this.clearQuerys();
    this.clearPaths();
    this.clearForms();
  }
}
