// AUTO GENERATED by svelte-reflector. DO NOT EDIT.
import api from "$lib/api";
import { PUBLIC_ENVIRONMENT } from "$env/static/public";
import { Behavior, type ApiErrorResponse } from "$reflector/reflector.svelte";

import {
  type NotificationController_listResponseInterface,
  NotificationController_listResponse,
} from "./notification.schema.svelte";

export abstract class NotificationModule {
  loading = $state<boolean>(false);
  notificationController_list = $state<
    NotificationController_listResponse | undefined
  >();

  /**  */
  protected async _listAllRun(params?: {
    behavior?: Behavior<
      NotificationController_listResponseInterface,
      ApiErrorResponse
    >;
  }) {
    const behavior = params?.behavior ?? new Behavior();
    const { onError, onSuccess } = behavior;

    this.loading = true;

    const endpoint = `notifications`;

    try {
      const response = await api.get<
        NotificationController_listResponseInterface,
        unknown
      >({
        endpoint,
      });

      this.notificationController_list =
        new NotificationController_listResponse({ data: response });

      await onSuccess?.(response);

      return {
        ok: true,
        data: new NotificationController_listResponse({ data: response }),
      };
    } catch (e) {
      let parsedError: ApiErrorResponse;
      try {
        parsedError = JSON.parse((e as Error).message) as ApiErrorResponse;
      } catch {
        parsedError = {
          error: "unknown",
          message: (e as Error).message ?? String(e),
        };
      }
      await onError?.(parsedError);
      return { ok: false, error: parsedError };
    } finally {
      this.loading = false;
    }
  }

  /** @deprecated use `_listAllRun()` — returns a discriminated ApiResult */
  protected async _listAll(params?: {
    behavior?: Behavior<
      NotificationController_listResponseInterface,
      ApiErrorResponse
    >;
  }) {
    const res = await this._listAllRun(params);
    return res.ok ? res.data : undefined;
  }

  protected clearNotificationController_list() {
    this.notificationController_list = undefined;
  }

  protected reset() {
    this.clearNotificationController_list();
  }
}
