// AUTO GENERATED by svelte-reflector. DO NOT EDIT.
import api from "$lib/api";
import { PUBLIC_ENVIRONMENT } from "$env/static/public";
import { page } from "$app/state";
import {
  Behavior,
  genericArrayBundler,
  isFormValid,
  QueryBuilder,
  type ApiErrorResponse,
  setQueryGroup,
} from "$reflector/reflector.svelte";
import mockedParams from "$reflector/mocked-params.svelte";

import {
  type AiChatTenantController_listResponseInterface,
  AiChatTenantController_listResponse,
  AiChatTenantController_createBody,
  type AiChatInterface,
  AiChat,
  type AiChatTenantController_getMessagesResponseInterface,
  AiChatTenantController_getMessagesResponse,
} from "./ai-chat-tenant.schema.svelte";

class Querys {
  readonly page = $derived(new QueryBuilder({ key: "page" }));
  readonly limit = $derived(new QueryBuilder({ key: "limit" }));

  constructor() {
    setQueryGroup([
      { key: "page", value: 1 },
      { key: "limit", value: 10 },
    ]);
  }

  bundle() {
    return {
      page: this.page?.value,
      limit: this.limit?.value,
    };
  }
}
class Paths {
  readonly chatId = $derived.by(() =>
    "chatId" in page.params ? page.params.chatId : mockedParams.chatId,
  ) as string | null;
}

export abstract class AiChatTenantModule {
  loading = $state<boolean>(false);
  totalPages = $state<number>(1);
  listAiChats = $state<AiChatTenantController_listResponse["data"]>([]);
  bundledListAiChats = $derived(genericArrayBundler(this.listAiChats));
  listMessages = $state<AiChatTenantController_getMessagesResponse["data"]>([]);
  bundledListMessages = $derived(genericArrayBundler(this.listMessages));
  querys = new Querys();
  paths = new Paths();
  forms = $state({
    create: new AiChatTenantController_createBody(),
  });

  constructor(params?: { empty: boolean }) {
    const isEmpty = params?.empty ?? PUBLIC_ENVIRONMENT !== "DEV";
    this.forms = this.buildForms(isEmpty);
  }

  private buildForms(isEmpty: boolean) {
    if (!isEmpty) return this.forms;

    return { create: new AiChatTenantController_createBody({ empty: true }) };
  }

  /**  */
  protected async _listAll(params?: {
    behavior?: Behavior<
      AiChatTenantController_listResponseInterface,
      ApiErrorResponse
    >;
  }) {
    const behavior = params?.behavior ?? new Behavior();
    const { onError, onSuccess } = behavior;

    this.loading = true;
    const { page, limit } = this.querys.bundle();
    const endpoint = `tenant/ai-chat`;

    try {
      const response = await api.get<
        AiChatTenantController_listResponseInterface,
        unknown
      >({
        endpoint,
        queryData: { page, limit },
      });
      this.listAiChats = AiChatTenantController_listResponse.from(
        response.data,
      );
      this.totalPages = response.totalPages;

      await onSuccess?.(response);

      return this.listAiChats;
    } catch (e) {
      let parsedError: ApiErrorResponse;
      try {
        parsedError = JSON.parse((e as Error).message) as ApiErrorResponse;
      } catch {
        parsedError = {
          error: "unknown",
          message: (e as Error).message ?? String(e),
        };
      }
      return await onError?.(parsedError);
    } finally {
      this.loading = false;
    }
  }

  /**  */
  protected async _create(params?: {
    behavior?: Behavior<AiChatInterface, ApiErrorResponse>;
  }) {
    const behavior = params?.behavior ?? new Behavior();
    const { onError, onSuccess } = behavior;

    this.loading = true;

    const endpoint = `tenant/ai-chat`;

    const data = this.forms.create.bundle();

    try {
      const response = await api.post<AiChatInterface>({
        endpoint,
        data,
      });

      await onSuccess?.(response);

      return new AiChat({ data: response });
    } catch (e) {
      let parsedError: ApiErrorResponse;
      try {
        parsedError = JSON.parse((e as Error).message) as ApiErrorResponse;
      } catch {
        parsedError = {
          error: "unknown",
          message: (e as Error).message ?? String(e),
        };
      }
      return await onError?.(parsedError);
    } finally {
      this.loading = false;
    }
  }

  /**  */
  protected async _getMessages(params?: {
    behavior?: Behavior<
      AiChatTenantController_getMessagesResponseInterface,
      ApiErrorResponse
    >;
    paths?: {
      chatId: string;
    };
  }) {
    const behavior = params?.behavior ?? new Behavior();
    const { onError, onSuccess } = behavior;

    this.loading = true;
    const { page } = this.querys.bundle();
    const { chatId } = params?.paths ?? this.paths;
    const endpoint = `tenant/ai-chat/${chatId}/messages`;

    try {
      const response = await api.get<
        AiChatTenantController_getMessagesResponseInterface,
        unknown
      >({
        endpoint,
        queryData: { page },
      });
      this.listMessages = AiChatTenantController_getMessagesResponse.from(
        response.data,
      );
      this.totalPages = response.totalPages;

      await onSuccess?.(response);

      return this.listMessages;
    } catch (e) {
      let parsedError: ApiErrorResponse;
      try {
        parsedError = JSON.parse((e as Error).message) as ApiErrorResponse;
      } catch {
        parsedError = {
          error: "unknown",
          message: (e as Error).message ?? String(e),
        };
      }
      return await onError?.(parsedError);
    } finally {
      this.loading = false;
    }
  }

  protected clearListAiChats() {
    this.listAiChats = [];
  }

  protected clearListMessages() {
    this.listMessages = [];
  }

  protected clearQuerys() {
    this.querys = new Querys();
  }

  protected clearPaths() {
    this.paths = new Paths();
  }

  protected clearForms() {
    this.forms = this.buildForms(true);
  }

  protected reset() {
    this.clearListAiChats();
    this.clearListMessages();
    this.clearQuerys();
    this.clearPaths();
    this.clearForms();
  }
}
