// AUTO GENERATED by svelte-reflector. DO NOT EDIT.
import api from "$lib/api";
import { PUBLIC_ENVIRONMENT } from "$env/static/public";
import { page } from "$app/state";
import {
  Behavior,
  genericArrayBundler,
  QueryBuilder,
  bundleStrict,
  type ApiErrorResponse,
} from "$reflector/reflector.svelte";
import mockedParams from "$reflector/mocked-params.svelte";

import {
  type WidgetController_listResponseInterface,
  WidgetController_listResponse,
  type WidgetInterface,
  Widget,
  type ENUM_WIDGET_SHAPEInterface,
  ENUM_WIDGET_SHAPE,
} from "./widget.schema.svelte";

class Querys {
  readonly page = new QueryBuilder({ key: "page" });
  readonly limit = new QueryBuilder({ key: "limit", persist: true });

  bundle() {
    return bundleStrict({
      page: this.page?.value,
      limit: this.limit?.value,
    });
  }
}
class Paths {
  readonly widgetId = $derived.by(() =>
    "widgetId" in page.params ? page.params.widgetId : mockedParams.widgetId,
  ) as string | null;
}

export abstract class WidgetModule {
  loading = $state<boolean>(false);
  totalPages = $state<number>(1);
  list = $state<WidgetController_listResponse["data"]>([]);
  bundledList = $derived(genericArrayBundler(this.list));
  widgetEntity = $state<Widget | undefined>();
  eNUM_WIDGET_SHAPE = $state<ENUM_WIDGET_SHAPE | undefined>();
  querys = new Querys();
  paths = new Paths();

  /**  */
  protected async _listAllRun(params?: {
    behavior?: Behavior<
      WidgetController_listResponseInterface,
      ApiErrorResponse
    >;
    queryOverride?: {
      page?: string | null;
      limit?: string | null;
    };
  }) {
    const behavior = params?.behavior ?? new Behavior();
    const { onError, onSuccess } = behavior;

    this.loading = true;
    const { page, limit } = params?.queryOverride ?? this.querys.bundle();
    const endpoint = `widgets`;

    try {
      const response = await api.get<
        WidgetController_listResponseInterface,
        unknown
      >({
        endpoint,
        queryData: { page, limit },
      });
      this.list = WidgetController_listResponse.from(response.data);
      this.totalPages = response.totalPages;

      await onSuccess?.(response);

      return { ok: true, data: this.list };
    } catch (e) {
      let parsedError: ApiErrorResponse;
      try {
        parsedError = JSON.parse((e as Error).message) as ApiErrorResponse;
      } catch {
        parsedError = {
          error: "unknown",
          message: (e as Error).message ?? String(e),
        };
      }
      await onError?.(parsedError);
      return { ok: false, error: parsedError };
    } finally {
      this.loading = false;
    }
  }

  /** @deprecated use `_listAllRun()` — returns a discriminated ApiResult */
  protected async _listAll(params?: {
    behavior?: Behavior<
      WidgetController_listResponseInterface,
      ApiErrorResponse
    >;
    queryOverride?: {
      page?: string | null;
      limit?: string | null;
    };
  }) {
    const res = await this._listAllRun(params);
    return res.ok ? res.data : undefined;
  }

  /**  */
  protected async _entityRun(params?: {
    behavior?: Behavior<WidgetInterface, ApiErrorResponse>;
    paths?: {
      widgetId: string;
    };
  }) {
    const behavior = params?.behavior ?? new Behavior();
    const { onError, onSuccess } = behavior;

    this.loading = true;
    const { widgetId } = params?.paths ?? this.paths;
    const endpoint = `widgets/${widgetId}`;

    try {
      const response = await api.get<WidgetInterface, unknown>({
        endpoint,
      });

      this.widgetEntity = new Widget({ data: response });

      await onSuccess?.(response);

      return { ok: true, data: new Widget({ data: response }) };
    } catch (e) {
      let parsedError: ApiErrorResponse;
      try {
        parsedError = JSON.parse((e as Error).message) as ApiErrorResponse;
      } catch {
        parsedError = {
          error: "unknown",
          message: (e as Error).message ?? String(e),
        };
      }
      await onError?.(parsedError);
      return { ok: false, error: parsedError };
    } finally {
      this.loading = false;
    }
  }

  /** @deprecated use `_entityRun()` — returns a discriminated ApiResult */
  protected async _entity(params?: {
    behavior?: Behavior<WidgetInterface, ApiErrorResponse>;
    paths?: {
      widgetId: string;
    };
  }) {
    const res = await this._entityRun(params);
    return res.ok ? res.data : undefined;
  }

  /**  */
  protected async _removeRun(params?: {
    behavior?: Behavior<null, ApiErrorResponse>;
    paths?: {
      widgetId: string;
    };
  }) {
    const behavior = params?.behavior ?? new Behavior();
    const { onError, onSuccess } = behavior;

    this.loading = true;
    const { widgetId } = params?.paths ?? this.paths;
    const endpoint = `widgets/${widgetId}`;

    try {
      const response = await api.delete<null, unknown>({
        endpoint,
      });

      await onSuccess?.(response);

      return { ok: true, data: null };
    } catch (e) {
      let parsedError: ApiErrorResponse;
      try {
        parsedError = JSON.parse((e as Error).message) as ApiErrorResponse;
      } catch {
        parsedError = {
          error: "unknown",
          message: (e as Error).message ?? String(e),
        };
      }
      await onError?.(parsedError);
      return { ok: false, error: parsedError };
    } finally {
      this.loading = false;
    }
  }

  /** @deprecated use `_removeRun()` — returns a discriminated ApiResult */
  protected async _remove(params?: {
    behavior?: Behavior<null, ApiErrorResponse>;
    paths?: {
      widgetId: string;
    };
  }) {
    const res = await this._removeRun(params);
    return res.ok ? res.data : undefined;
  }

  /**  */
  protected async _kindRun(params?: {
    behavior?: Behavior<string, ApiErrorResponse>;
    paths?: {
      widgetId: string;
    };
  }) {
    const behavior = params?.behavior ?? new Behavior();
    const { onError, onSuccess } = behavior;

    this.loading = true;
    const { widgetId } = params?.paths ?? this.paths;
    const endpoint = `widgets/${widgetId}/kind`;

    try {
      const response = await api.get<string, unknown>({
        endpoint,
      });

      await onSuccess?.(response);

      return { ok: true, data: response };
    } catch (e) {
      let parsedError: ApiErrorResponse;
      try {
        parsedError = JSON.parse((e as Error).message) as ApiErrorResponse;
      } catch {
        parsedError = {
          error: "unknown",
          message: (e as Error).message ?? String(e),
        };
      }
      await onError?.(parsedError);
      return { ok: false, error: parsedError };
    } finally {
      this.loading = false;
    }
  }

  /** @deprecated use `_kindRun()` — returns a discriminated ApiResult */
  protected async _kind(params?: {
    behavior?: Behavior<string, ApiErrorResponse>;
    paths?: {
      widgetId: string;
    };
  }) {
    const res = await this._kindRun(params);
    return res.ok ? res.data : undefined;
  }

  /**  */
  protected async _shapeRun(params?: {
    behavior?: Behavior<ENUM_WIDGET_SHAPEInterface, ApiErrorResponse>;
    paths?: {
      widgetId: string;
    };
  }) {
    const behavior = params?.behavior ?? new Behavior();
    const { onError, onSuccess } = behavior;

    this.loading = true;
    const { widgetId } = params?.paths ?? this.paths;
    const endpoint = `widgets/${widgetId}/shape`;

    try {
      const response = await api.get<ENUM_WIDGET_SHAPE, unknown>({
        endpoint,
      });

      this.eNUM_WIDGET_SHAPE = new ENUM_WIDGET_SHAPE({ data: response });

      await onSuccess?.(response);

      return { ok: true, data: response };
    } catch (e) {
      let parsedError: ApiErrorResponse;
      try {
        parsedError = JSON.parse((e as Error).message) as ApiErrorResponse;
      } catch {
        parsedError = {
          error: "unknown",
          message: (e as Error).message ?? String(e),
        };
      }
      await onError?.(parsedError);
      return { ok: false, error: parsedError };
    } finally {
      this.loading = false;
    }
  }

  /** @deprecated use `_shapeRun()` — returns a discriminated ApiResult */
  protected async _shape(params?: {
    behavior?: Behavior<ENUM_WIDGET_SHAPEInterface, ApiErrorResponse>;
    paths?: {
      widgetId: string;
    };
  }) {
    const res = await this._shapeRun(params);
    return res.ok ? res.data : undefined;
  }

  protected clearList() {
    this.list = [];
  }

  protected clearWidgetEntity() {
    this.widgetEntity = undefined;
  }

  protected clearENUM_WIDGET_SHAPE() {
    this.eNUM_WIDGET_SHAPE = undefined;
  }

  protected clearQuerys() {
    this.querys = new Querys();
  }

  protected clearPaths() {
    this.paths = new Paths();
  }

  protected reset() {
    this.clearList();
    this.clearWidgetEntity();
    this.clearENUM_WIDGET_SHAPE();
    this.clearQuerys();
    this.clearPaths();
  }
}
