// AUTO GENERATED by svelte-reflector. DO NOT EDIT.
import api from "$lib/api";
import { PUBLIC_ENVIRONMENT } from "$env/static/public";
import {
  Behavior,
  genericArrayBundler,
  QueryBuilder,
  bundleStrict,
  type ApiErrorResponse,
} from "$reflector/reflector.svelte";

import {
  type SimplePurchaseResponseInterface,
  SimplePurchaseResponse,
  type CustomerDashboardResponseInterface,
  CustomerDashboardResponse,
} from "./dashboard.schema.svelte";

class Querys {
  readonly page = new QueryBuilder({ key: "page" });

  bundle() {
    return bundleStrict({
      page: this.page?.value,
    });
  }
}

export abstract class DashboardModule {
  loading = $state<boolean>(false);
  totalPages = $state<number>(1);
  listSimples = $state<SimplePurchaseResponse["data"]>([]);
  bundledListSimples = $derived(genericArrayBundler(this.listSimples));
  listRiches = $state<CustomerDashboardResponse["data"]>([]);
  bundledListRiches = $derived(genericArrayBundler(this.listRiches));
  querys = new Querys();

  /**  */
  protected async _listSimpleRun(params?: {
    behavior?: Behavior<SimplePurchaseResponseInterface, ApiErrorResponse>;
    queryOverride?: {
      page?: string | null;
    };
  }) {
    const behavior = params?.behavior ?? new Behavior();
    const { onError, onSuccess } = behavior;

    this.loading = true;
    const { page } = params?.queryOverride ?? this.querys.bundle();
    const endpoint = `dashboard/simple`;

    try {
      const response = await api.get<SimplePurchaseResponseInterface, unknown>({
        endpoint,
        queryData: { page },
      });
      this.listSimples = SimplePurchaseResponse.from(response.data);
      this.totalPages = response.totalPages;

      await onSuccess?.(response);

      return { ok: true, data: this.listSimples };
    } catch (e) {
      let parsedError: ApiErrorResponse;
      try {
        parsedError = JSON.parse((e as Error).message) as ApiErrorResponse;
      } catch {
        parsedError = {
          error: "unknown",
          message: (e as Error).message ?? String(e),
        };
      }
      await onError?.(parsedError);
      return { ok: false, error: parsedError };
    } finally {
      this.loading = false;
    }
  }

  /** @deprecated use `_listSimpleRun()` — returns a discriminated ApiResult */
  protected async _listSimple(params?: {
    behavior?: Behavior<SimplePurchaseResponseInterface, ApiErrorResponse>;
    queryOverride?: {
      page?: string | null;
    };
  }) {
    const res = await this._listSimpleRun(params);
    return res.ok ? res.data : undefined;
  }

  /**  */
  protected async _listRichRun(params?: {
    behavior?: Behavior<CustomerDashboardResponseInterface, ApiErrorResponse>;
    queryOverride?: {
      page?: string | null;
    };
  }) {
    const behavior = params?.behavior ?? new Behavior();
    const { onError, onSuccess } = behavior;

    this.loading = true;
    const { page } = params?.queryOverride ?? this.querys.bundle();
    const endpoint = `dashboard/rich`;

    try {
      const response = await api.get<
        CustomerDashboardResponseInterface,
        unknown
      >({
        endpoint,
        queryData: { page },
      });
      this.listRiches = CustomerDashboardResponse.from(response.data);
      this.totalPages = response.totalPages;

      await onSuccess?.(response);

      return { ok: true, data: this.listRiches };
    } catch (e) {
      let parsedError: ApiErrorResponse;
      try {
        parsedError = JSON.parse((e as Error).message) as ApiErrorResponse;
      } catch {
        parsedError = {
          error: "unknown",
          message: (e as Error).message ?? String(e),
        };
      }
      await onError?.(parsedError);
      return { ok: false, error: parsedError };
    } finally {
      this.loading = false;
    }
  }

  /** @deprecated use `_listRichRun()` — returns a discriminated ApiResult */
  protected async _listRich(params?: {
    behavior?: Behavior<CustomerDashboardResponseInterface, ApiErrorResponse>;
    queryOverride?: {
      page?: string | null;
    };
  }) {
    const res = await this._listRichRun(params);
    return res.ok ? res.data : undefined;
  }

  protected clearListSimples() {
    this.listSimples = [];
  }

  protected clearListRiches() {
    this.listRiches = [];
  }

  protected clearQuerys() {
    this.querys = new Querys();
  }

  protected reset() {
    this.clearListSimples();
    this.clearListRiches();
    this.clearQuerys();
  }
}
