// AUTO GENERATED by svelte-reflector. DO NOT EDIT.
import api from "$lib/api";
import { PUBLIC_ENVIRONMENT } from "$env/static/public";
import { page } from "$app/state";
import {
  Behavior,
  QueryBuilder,
  bundleStrict,
  isFormValid,
  type ApiErrorResponse,
  type ApiCallParams,
} from "$reflector/reflector.svelte";
import mockedParams from "$reflector/mocked-params.svelte";

import {
  type UserController_listResponseInterface,
  UserController_listResponse,
  UserController_createBody,
  type UserInterface,
  User,
} from "./user.schema.svelte";

class ListAllQuerys {
  readonly limit = new QueryBuilder({ key: "limit", defaultValue: 10 });

  bundle() {
    return bundleStrict({
      limit: this.limit?.value,
    });
  }
}

export class ListAll {
  loading = $state<boolean>(false);
  data = $state<UserController_listResponse | undefined>();
  querys = new ListAllQuerys();

  /**  */
  async call(
    params?: ApiCallParams<
      UserController_listResponseInterface,
      void,
      { limit?: string | null }
    >,
  ) {
    const behavior = params?.behavior ?? new Behavior();
    const { onError, onSuccess } = behavior;

    this.loading = true;
    const { limit } = params?.queryOverride ?? this.querys.bundle();
    const endpoint = `users`;

    try {
      const response = await api.get<
        UserController_listResponseInterface,
        unknown
      >({
        endpoint,
        queryData: { limit },
      });

      this.data = new UserController_listResponse({ data: response });

      await onSuccess?.(response);

      return new UserController_listResponse({ data: response });
    } catch (e) {
      let parsedError: ApiErrorResponse;
      try {
        parsedError = JSON.parse((e as Error).message) as ApiErrorResponse;
      } catch {
        parsedError = {
          error: "unknown",
          message: (e as Error).message ?? String(e),
        };
      }
      return await onError?.(parsedError);
    } finally {
      this.loading = false;
    }
  }

  reset() {
    this.data = undefined;
    this.querys = new ListAllQuerys();
  }
}

export class Create {
  loading = $state<boolean>(false);
  form = new UserController_createBody();

  /**  */
  async call(params?: ApiCallParams<UserInterface>) {
    const behavior = params?.behavior ?? new Behavior();
    const { onError, onSuccess } = behavior;

    this.loading = true;

    const endpoint = `users`;

    const data = this.form.bundle();

    try {
      const response = await api.post<UserInterface>({
        endpoint,
        data,
      });

      await onSuccess?.(response);

      return new User({ data: response });
    } catch (e) {
      let parsedError: ApiErrorResponse;
      try {
        parsedError = JSON.parse((e as Error).message) as ApiErrorResponse;
      } catch {
        parsedError = {
          error: "unknown",
          message: (e as Error).message ?? String(e),
        };
      }
      return await onError?.(parsedError);
    } finally {
      this.loading = false;
    }
  }

  reset() {
    this.form.reset();
  }
}

class EntityPaths {
  readonly id = $derived.by(() =>
    "id" in page.params ? page.params.id : mockedParams.id,
  ) as string | null;
}

export class Entity {
  loading = $state<boolean>(false);
  data = $state<User | undefined>();
  paths = new EntityPaths();

  /**  */
  async call(params?: ApiCallParams<UserInterface, { id: string }>) {
    const behavior = params?.behavior ?? new Behavior();
    const { onError, onSuccess } = behavior;

    this.loading = true;
    const { id } = params?.paths ?? this.paths;
    const endpoint = `users/${id}`;

    try {
      const response = await api.get<UserInterface, unknown>({
        endpoint,
      });

      this.data = new User({ data: response });

      await onSuccess?.(response);

      return new User({ data: response });
    } catch (e) {
      let parsedError: ApiErrorResponse;
      try {
        parsedError = JSON.parse((e as Error).message) as ApiErrorResponse;
      } catch {
        parsedError = {
          error: "unknown",
          message: (e as Error).message ?? String(e),
        };
      }
      return await onError?.(parsedError);
    } finally {
      this.loading = false;
    }
  }

  reset() {
    this.data = undefined;
    this.paths = new EntityPaths();
  }
}

class RemovePaths {
  readonly id = $derived.by(() =>
    "id" in page.params ? page.params.id : mockedParams.id,
  ) as string | null;
}

export class Remove {
  loading = $state<boolean>(false);
  data = $state<unknown>(undefined);
  paths = new RemovePaths();

  /**  */
  async call(params?: ApiCallParams<null, { id: string }>) {
    const behavior = params?.behavior ?? new Behavior();
    const { onError, onSuccess } = behavior;

    this.loading = true;
    const { id } = params?.paths ?? this.paths;
    const endpoint = `users/${id}`;

    try {
      const response = await api.delete<null, unknown>({
        endpoint,
      });

      await onSuccess?.(response);

      return null;
    } catch (e) {
      let parsedError: ApiErrorResponse;
      try {
        parsedError = JSON.parse((e as Error).message) as ApiErrorResponse;
      } catch {
        parsedError = {
          error: "unknown",
          message: (e as Error).message ?? String(e),
        };
      }
      return await onError?.(parsedError);
    } finally {
      this.loading = false;
    }
  }

  reset() {
    this.data = undefined;
    this.paths = new RemovePaths();
  }
}
