// AUTO GENERATED by svelte-reflector. DO NOT EDIT.
import api from "$lib/api";
import { PUBLIC_ENVIRONMENT } from "$env/static/public";
import {
  Behavior,
  isFormValid,
  type ApiErrorResponse,
} from "$reflector/reflector.svelte";

import {
  BatchCreatePackageDto,
  type BatchCreatePackageDtoInterface,
} from "./package.schema.svelte";

export abstract class PackageModule {
  loading = $state<boolean>(false);
  forms = $state({
    create: new BatchCreatePackageDto(),
  });

  constructor(params?: { empty: boolean }) {
    const isEmpty = params?.empty ?? PUBLIC_ENVIRONMENT !== "DEV";
    this.forms = this.buildForms(isEmpty);
  }

  private buildForms(isEmpty: boolean) {
    if (!isEmpty) return this.forms;

    return { create: new BatchCreatePackageDto({ empty: true }) };
  }

  /**  */
  protected async _create(params?: {
    behavior?: Behavior<BatchCreatePackageDtoInterface, ApiErrorResponse>;
  }) {
    const behavior = params?.behavior ?? new Behavior();
    const { onError, onSuccess } = behavior;

    this.loading = true;

    const endpoint = `packages`;

    const data = this.forms.create.bundle();

    try {
      const response = await api.post<BatchCreatePackageDtoInterface>({
        endpoint,
        data,
      });

      await onSuccess?.(response);

      return new BatchCreatePackageDto({ data: response });
    } catch (e) {
      let parsedError: ApiErrorResponse;
      try {
        parsedError = JSON.parse((e as Error).message) as ApiErrorResponse;
      } catch {
        parsedError = {
          error: "unknown",
          message: (e as Error).message ?? String(e),
        };
      }
      return await onError?.(parsedError);
    } finally {
      this.loading = false;
    }
  }

  protected clearForms() {
    this.forms = this.buildForms(true);
  }

  protected reset() {
    this.clearForms();
  }
}
