// AUTO GENERATED by svelte-reflector. DO NOT EDIT.
import api from "$lib/api";
import { PUBLIC_ENVIRONMENT } from "$env/static/public";
import {
  Behavior,
  QueryBuilder,
  EnumQueryBuilder,
  bundleStrict,
  type ApiErrorResponse,
} from "$reflector/reflector.svelte";

import { ENUM_ITEM_ENTITY_STATUSES } from "$reflector/enums";
import {
  type ItemController_listResponseInterface,
  ItemController_listResponse,
} from "./item.schema.svelte";

class Querys {
  readonly categoriesIds = new EnumQueryBuilder<string>({
    key: "categoriesIds",
    defaultValues: [],
  });
  readonly pageNumbers = new EnumQueryBuilder<number>({
    key: "pageNumbers",
    defaultValues: [],
  });
  readonly statuses = new EnumQueryBuilder<ENUM_ITEM_ENTITY_STATUSES>({
    key: "statuses",
    defaultValues: [],
  });
  readonly badField = new QueryBuilder({ key: "badField" });

  bundle() {
    return bundleStrict({
      categoriesIds: this.categoriesIds?.values,
      pageNumbers: this.pageNumbers?.values,
      statuses: this.statuses?.values,
      badField: this.badField?.value,
    });
  }
}

export abstract class ItemModule {
  loading = $state<boolean>(false);
  itemController_list = $state<ItemController_listResponse | undefined>();
  querys = new Querys();

  /**  */
  protected async _listAllRun(params?: {
    behavior?: Behavior<ItemController_listResponseInterface, ApiErrorResponse>;
    queryOverride?: {
      categoriesIds?: string[];
      pageNumbers?: number[];
      statuses?: ENUM_ITEM_ENTITY_STATUSES[];
      badField?: string | null;
    };
  }) {
    const behavior = params?.behavior ?? new Behavior();
    const { onError, onSuccess } = behavior;

    this.loading = true;
    const { categoriesIds, pageNumbers, statuses, badField } =
      params?.queryOverride ?? this.querys.bundle();
    const endpoint = `items`;

    try {
      const response = await api.get<
        ItemController_listResponseInterface,
        unknown
      >({
        endpoint,
        queryData: { categoriesIds, pageNumbers, statuses, badField },
      });

      this.itemController_list = new ItemController_listResponse({
        data: response,
      });

      await onSuccess?.(response);

      return {
        ok: true,
        data: new ItemController_listResponse({ data: response }),
      };
    } catch (e) {
      let parsedError: ApiErrorResponse;
      try {
        parsedError = JSON.parse((e as Error).message) as ApiErrorResponse;
      } catch {
        parsedError = {
          error: "unknown",
          message: (e as Error).message ?? String(e),
        };
      }
      await onError?.(parsedError);
      return { ok: false, error: parsedError };
    } finally {
      this.loading = false;
    }
  }

  /** @deprecated use `_listAllRun()` — returns a discriminated ApiResult */
  protected async _listAll(params?: {
    behavior?: Behavior<ItemController_listResponseInterface, ApiErrorResponse>;
    queryOverride?: {
      categoriesIds?: string[];
      pageNumbers?: number[];
      statuses?: ENUM_ITEM_ENTITY_STATUSES[];
      badField?: string | null;
    };
  }) {
    const res = await this._listAllRun(params);
    return res.ok ? res.data : undefined;
  }

  protected clearItemController_list() {
    this.itemController_list = undefined;
  }

  protected clearQuerys() {
    this.querys = new Querys();
  }

  protected reset() {
    this.clearItemController_list();
    this.clearQuerys();
  }
}
