// AUTO GENERATED by svelte-reflector. DO NOT EDIT.
import api from "$lib/api";
import { PUBLIC_ENVIRONMENT } from "$env/static/public";
import { Behavior, type ApiErrorResponse } from "$reflector/reflector.svelte";

import {
  type ArrayController_primitivesResponseInterface,
  ArrayController_primitivesResponse,
  type ArrayController_enumsResponseInterface,
  ArrayController_enumsResponse,
  type ArrayController_inlineResponseInterface,
  ArrayController_inlineResponse,
  type ArrayController_genericResponseInterface,
  ArrayController_genericResponse,
} from "./array.schema.svelte";

export abstract class ArrayModule {
  loading = $state<boolean>(false);
  arrayController_primitives = $state<
    ArrayController_primitivesResponse | undefined
  >();
  arrayController_enums = $state<ArrayController_enumsResponse | undefined>();
  arrayController_inline = $state<ArrayController_inlineResponse | undefined>();
  arrayController_generic = $state<
    ArrayController_genericResponse | undefined
  >();

  /**  */
  protected async _primitives(params?: {
    behavior?: Behavior<
      ArrayController_primitivesResponseInterface,
      ApiErrorResponse
    >;
  }) {
    const behavior = params?.behavior ?? new Behavior();
    const { onError, onSuccess } = behavior;

    this.loading = true;

    const endpoint = `arr/primitives`;

    try {
      const response = await api.get<
        ArrayController_primitivesResponseInterface,
        unknown
      >({
        endpoint,
      });

      this.arrayController_primitives = new ArrayController_primitivesResponse({
        data: response,
      });

      await onSuccess?.(response);

      return new ArrayController_primitivesResponse({ data: response });
    } catch (e) {
      let parsedError: ApiErrorResponse;
      try {
        parsedError = JSON.parse((e as Error).message) as ApiErrorResponse;
      } catch {
        parsedError = {
          error: "unknown",
          message: (e as Error).message ?? String(e),
        };
      }
      return await onError?.(parsedError);
    } finally {
      this.loading = false;
    }
  }

  /**  */
  protected async _enums(params?: {
    behavior?: Behavior<
      ArrayController_enumsResponseInterface,
      ApiErrorResponse
    >;
  }) {
    const behavior = params?.behavior ?? new Behavior();
    const { onError, onSuccess } = behavior;

    this.loading = true;

    const endpoint = `arr/enums`;

    try {
      const response = await api.get<
        ArrayController_enumsResponseInterface,
        unknown
      >({
        endpoint,
      });

      this.arrayController_enums = new ArrayController_enumsResponse({
        data: response,
      });

      await onSuccess?.(response);

      return new ArrayController_enumsResponse({ data: response });
    } catch (e) {
      let parsedError: ApiErrorResponse;
      try {
        parsedError = JSON.parse((e as Error).message) as ApiErrorResponse;
      } catch {
        parsedError = {
          error: "unknown",
          message: (e as Error).message ?? String(e),
        };
      }
      return await onError?.(parsedError);
    } finally {
      this.loading = false;
    }
  }

  /**  */
  protected async _inline(params?: {
    behavior?: Behavior<
      ArrayController_inlineResponseInterface,
      ApiErrorResponse
    >;
  }) {
    const behavior = params?.behavior ?? new Behavior();
    const { onError, onSuccess } = behavior;

    this.loading = true;

    const endpoint = `arr/inline`;

    try {
      const response = await api.get<
        ArrayController_inlineResponseInterface,
        unknown
      >({
        endpoint,
      });

      this.arrayController_inline = new ArrayController_inlineResponse({
        data: response,
      });

      await onSuccess?.(response);

      return new ArrayController_inlineResponse({ data: response });
    } catch (e) {
      let parsedError: ApiErrorResponse;
      try {
        parsedError = JSON.parse((e as Error).message) as ApiErrorResponse;
      } catch {
        parsedError = {
          error: "unknown",
          message: (e as Error).message ?? String(e),
        };
      }
      return await onError?.(parsedError);
    } finally {
      this.loading = false;
    }
  }

  /**  */
  protected async _generic(params?: {
    behavior?: Behavior<
      ArrayController_genericResponseInterface,
      ApiErrorResponse
    >;
  }) {
    const behavior = params?.behavior ?? new Behavior();
    const { onError, onSuccess } = behavior;

    this.loading = true;

    const endpoint = `arr/generic`;

    try {
      const response = await api.get<
        ArrayController_genericResponseInterface,
        unknown
      >({
        endpoint,
      });

      this.arrayController_generic = new ArrayController_genericResponse({
        data: response,
      });

      await onSuccess?.(response);

      return new ArrayController_genericResponse({ data: response });
    } catch (e) {
      let parsedError: ApiErrorResponse;
      try {
        parsedError = JSON.parse((e as Error).message) as ApiErrorResponse;
      } catch {
        parsedError = {
          error: "unknown",
          message: (e as Error).message ?? String(e),
        };
      }
      return await onError?.(parsedError);
    } finally {
      this.loading = false;
    }
  }

  protected clearArrayController_primitives() {
    this.arrayController_primitives = undefined;
  }

  protected clearArrayController_enums() {
    this.arrayController_enums = undefined;
  }

  protected clearArrayController_inline() {
    this.arrayController_inline = undefined;
  }

  protected clearArrayController_generic() {
    this.arrayController_generic = undefined;
  }

  protected reset() {
    this.clearArrayController_primitives();
    this.clearArrayController_enums();
    this.clearArrayController_inline();
    this.clearArrayController_generic();
  }
}
