import type { ReflectorConfig } from "../config/ReflectorConfig.js";

// Gerenciamento de imports do módulo
export class ModuleImports {
  readonly imports: Set<string>;
  readonly reflectorImports: Set<string>;
  readonly enumImports: Set<string>;
  readonly mockedImports: Set<string>;

  private readonly config: ReflectorConfig;

  constructor(apiImport: string, config: ReflectorConfig) {
    this.config = config;
    this.imports = new Set([
      "// AUTO GENERATED by svelte-reflector. DO NOT EDIT.\n",
      `import api from "${apiImport}"`,
      `import { ${config.environmentFlag} } from '${config.environmentImport}'`,
    ]);

    this.reflectorImports = new Set<string>(["Behavior"]);
    this.enumImports = new Set<string>();
    this.mockedImports = new Set<string>();
  }

  addImport(importStr: string): void {
    this.imports.add(importStr);
  }

  addMockedImport(importStr: string): void {
    this.mockedImports.add(importStr);
  }

  addReflectorImport(importStr: string): void {
    this.reflectorImports.add(importStr);
  }

  addSetQueryGroupImport(): void {
    this.reflectorImports.add("setQueryGroup");
  }

  addEnumImport(enumName: string): void {
    this.enumImports.add(enumName);
  }

  addPageStateImport(): void {
    this.imports.add(`import { page } from "$app/state"`);
  }

  getImportsArray(): string[] {
    return Array.from(this.imports);
  }

  getReflectorImportsArray(): string[] {
    return Array.from(this.reflectorImports);
  }

  getEnumImportsArray(): string[] {
    return Array.from(this.enumImports);
  }

  hasEnumImports(): boolean {
    return this.enumImports.size > 0;
  }

  private hasMockedImports(): boolean {
    return this.mockedImports.size > 0;
  }

  getMockedImports(): string[] {
    return Array.from(this.mockedImports);
  }

  private readonly typeOnlyImports = new Set(["ApiCallParams"]);

  buildReflectorImportsLine(): string {
    const imports = this.getReflectorImportsArray();
    const regularImports = imports.filter(i => i !== "setQueryGroup" && !this.typeOnlyImports.has(i));
    const typeImports = imports.filter(i => this.typeOnlyImports.has(i));
    const hasSetQueryGroup = imports.includes("setQueryGroup");

    let result = `import { ${regularImports.join(", ")}, type ApiErrorResponse`;
    for (const t of typeImports) {
      result += `, type ${t}`;
    }
    if (hasSetQueryGroup) {
      result += `, setQueryGroup`;
    }
    result += ` } from "${this.config.reflectorAlias}/reflector.svelte";`;

    return result;
  }

  buildEnumImportsLine(): string {
    if (!this.hasEnumImports()) return "";
    return `import {${this.getEnumImportsArray().join(", ")} } from "${this.config.reflectorAlias}/enums"`;
  }

  buildMockedImportsLine(): string {
    if (!this.hasMockedImports()) return "";
    return `import ${this.getMockedImports()} from "${this.config.reflectorAlias}/mocked-params.svelte"`;
  }
}
