// AUTO GENERATED by svelte-reflector. DO NOT EDIT.
import api from "$lib/api";
import { PUBLIC_ENVIRONMENT } from "$env/static/public";
import { page } from "$app/state";
import {
  Behavior,
  QueryBuilder,
  type ApiErrorResponse,
} from "$reflector/reflector.svelte";
import mockedParams from "$reflector/mocked-params.svelte";

import {
  type CalendarController_getResponseInterface,
  CalendarController_getResponse,
} from "./calendar.schema.svelte";

class Paths {
  readonly id = $derived.by(() =>
    "id" in page.params ? page.params.id : mockedParams.id,
  ) as string | null;
}

export abstract class CalendarModule {
  loading = $state<boolean>(false);
  calendarController_get = $state<CalendarController_getResponse | undefined>();
  paths = new Paths();

  /**  */
  protected async _getRun(params?: {
    behavior?: Behavior<
      CalendarController_getResponseInterface,
      ApiErrorResponse
    >;
    paths?: {
      id: string;
    };
  }) {
    const behavior = params?.behavior ?? new Behavior();
    const { onError, onSuccess } = behavior;

    this.loading = true;
    const { id } = params?.paths ?? this.paths;
    const endpoint = `calendar/${id}`;

    try {
      const response = await api.get<
        CalendarController_getResponseInterface,
        unknown
      >({
        endpoint,
      });

      this.calendarController_get = new CalendarController_getResponse({
        data: response,
      });

      await onSuccess?.(response);

      return {
        ok: true,
        data: new CalendarController_getResponse({ data: response }),
      };
    } catch (e) {
      let parsedError: ApiErrorResponse;
      try {
        parsedError = JSON.parse((e as Error).message) as ApiErrorResponse;
      } catch {
        parsedError = {
          error: "unknown",
          message: (e as Error).message ?? String(e),
        };
      }
      await onError?.(parsedError);
      return { ok: false, error: parsedError };
    } finally {
      this.loading = false;
    }
  }

  /** @deprecated use `_getRun()` — returns a discriminated ApiResult */
  protected async _get(params?: {
    behavior?: Behavior<
      CalendarController_getResponseInterface,
      ApiErrorResponse
    >;
    paths?: {
      id: string;
    };
  }) {
    const res = await this._getRun(params);
    return res.ok ? res.data : undefined;
  }

  protected clearCalendarController_get() {
    this.calendarController_get = undefined;
  }

  protected clearPaths() {
    this.paths = new Paths();
  }

  protected reset() {
    this.clearCalendarController_get();
    this.clearPaths();
  }
}
